FEED-5785: add maxWaitTime and waitForNavTimeout to structures
splunk/terraform-provider-synthetics pull request #58
Opened 2024-08-22 22:10 UTC by sangn-splunk

Resolves https://splunk.atlassian.net/browse/FEED-5785

----

### Before the change?

* The documentation did not show `maxWaitTime` and `waitForNavTimeout`. 

![image](https://github.com/user-attachments/assets/e50dc56d-9a9f-4323-8f52-cd973beaafaf)

### After the change?

* The documentation show now show `maxWaitTime` and `waitForNavTimeout`. 

### Pull request checklist 
- [ ] Acceptance Tests have been updated, run (`make testacc`), and pasted in this PR (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

#### Acceptance Test Output

```

```

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

----

2024-08-23 13:19 UTC, greatestusername-splunk requested changes
Please update the test in `resource_browser_check_v2_test.go` to include these attributes and  `TestCheckResourceAttr` entries for each of them so they are included in the functional test? Thanks!

2024-08-23 13:27 UTC, greatestusername-splunk submitted a review, later dismissed

2024-08-23 13:27 UTC, greatestusername-splunk commented on synthetics/structures.go
> +				cl["wait_for_nav"] = checkStep.WaitForNavTimeout
Think "wait_for_nav" collides with another property here

2024-08-23 15:18 UTC, sangn-splunk commented on synthetics/structures.go
> +				cl["wait_for_nav"] = checkStep.WaitForNavTimeout
Fixed collision in 6ff88ca

2024-08-27 15:31 UTC, bchhay-splunk approved these changes
LGTM. thanks for fixing this!

2024-08-27 20:45 UTC, merged